import {
  ArrowLeft,
  ArrowRight,
  Award,
  Ban,
  Bell,
  Building2,
  Calculator,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Copy,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  FilterX,
  Handshake,
  Inbox,
  Info,
  KanbanSquare,
  KeyRound,
  LayoutDashboard,
  LogOut,
  type LucideIcon,
  Menu,
  MessageSquare,
  Pencil,
  Plus,
  Search,
  SearchX,
  Send,
  Settings2,
  Sparkles,
  Star,
  Telescope,
  Trash2,
  TrendingUp,
  TriangleAlert,
  UploadCloud,
  X,
} from "lucide-react";

/**
 * Names are kept close to what the design files used, so the mapping between a
 * mock and the code is obvious. The drawings themselves come from lucide —
 * one stroke weight, one grid, no mixed icon families.
 */
export const ICONS: Record<string, LucideIcon> = {
  add: Plus,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  auto_awesome: Sparkles,
  business: Building2,
  calculate: Calculator,
  check: Check,
  check_circle: CheckCircle2,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  content_copy: Copy,
  delete: Trash2,
  description: FileText,
  download: Download,
  draft: FileText,
  edit: Pencil,
  error: TriangleAlert,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  explore: Telescope,
  fact_check: CheckCircle2,
  filter_alt_off: FilterX,
  forum: MessageSquare,
  handshake: Handshake,
  info: Info,
  inbox: Inbox,
  key: KeyRound,
  logout: LogOut,
  menu: Menu,
  neurology: Sparkles,
  no_accounts: Ban,
  notifications: Bell,
  open_in_new: ExternalLink,
  picture_as_pdf: FileText,
  schedule: Clock,
  search: Search,
  search_off: SearchX,
  send: Send,
  space_dashboard: LayoutDashboard,
  star: Star,
  travel_explore: Telescope,
  trending_up: TrendingUp,
  tune: Settings2,
  upload_file: UploadCloud,
  view_kanban: KanbanSquare,
  visibility: Eye,
  visibility_off: EyeOff,
  warning: TriangleAlert,
  workspace_premium: Award,
};
